services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - default
    profiles:
      - full

  db:
    image: docker.io/library/postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=escapp
      - POSTGRES_PASSWORD=escapp
      - POSTGRES_DB=escapp
    networks:
      - default
    ports:
      - 5432:5432

volumes:
  db_data:

networks:
  default:
