apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cm.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
secretGenerator:
  - name: escapp
    namespace: escapp
    env: .env
